"""Contracts and shared execution context for classic issue checks."""

from .context import EvaluationContext, ToolCallable
from .contracts import (
    CACHE_STATUSES,
    CHECK_DECISIONS,
    CHECK_EXECUTION_STATUSES,
    EVIDENCE_LEVELS,
    EXPECTED_CLASSIC_CHECK_COUNT,
    TOOL_STATUSES,
    ClassicCheckResult,
    EvaluationResult,
    EvaluationSample,
    StableSerializable,
    ToolResult,
    ToolTraceEntry,
    stable_json_dumps,
    to_jsonable,
)
from .checks import (
    check_audio_quality_noise_artifacts,
    check_av_lip_sync,
    check_dialogue_speaker_binding,
    check_entity_count_spatial_composition,
    check_motion_physics_continuity,
    check_reference_subject_identity,
    check_remaining_hard_instruction_compliance,
    check_subtitle_text_logo_watermark,
    check_visual_quality_temporal_artifacts,
    check_voice_characteristics,
    classify_junk_test,
    classify_system_task_failure,
    evaluate_all_classic_checks,
)
from .harness import (
    TOOL_ORDER,
    build_evaluation_sample,
    evaluate_precomputed_tools,
)

__all__ = [
    "CACHE_STATUSES",
    "CHECK_DECISIONS",
    "CHECK_EXECUTION_STATUSES",
    "EVIDENCE_LEVELS",
    "EXPECTED_CLASSIC_CHECK_COUNT",
    "TOOL_STATUSES",
    "TOOL_ORDER",
    "ClassicCheckResult",
    "EvaluationContext",
    "EvaluationResult",
    "EvaluationSample",
    "StableSerializable",
    "ToolCallable",
    "ToolResult",
    "ToolTraceEntry",
    "build_evaluation_sample",
    "check_audio_quality_noise_artifacts",
    "check_av_lip_sync",
    "check_dialogue_speaker_binding",
    "check_entity_count_spatial_composition",
    "check_motion_physics_continuity",
    "check_reference_subject_identity",
    "check_remaining_hard_instruction_compliance",
    "check_subtitle_text_logo_watermark",
    "check_visual_quality_temporal_artifacts",
    "check_voice_characteristics",
    "classify_junk_test",
    "classify_system_task_failure",
    "evaluate_all_classic_checks",
    "evaluate_precomputed_tools",
    "stable_json_dumps",
    "to_jsonable",
]
